config/routes.rb
Gino::Application.routes.draw do
  resources :users

  devise_for :accounts

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(account)
    # Define abilities for the passed in user here. For example:
    #
    account ||= Account.new # guest user (not logged in)
    if account.user && account.user.god?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  belongs_to :user
  delegate :god, :god?, to: :user

  def name
    (user && user.full_name) || email
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  def full_name
    "#{first_name} #{last_name}"
  end
  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true

  has_one :account

  def god?
    god
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "sancho/application"
  # load_and_authorize_resource
  # before_action :authenticate_account!
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    current_account
  end
  
  def current_ability
    @current_ability ||= Ability.new(current_account)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource skip_load_resource only: [:create]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: I18n.t("#{controller_name}.controller.#{action_name}")
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: I18n.t("#{controller_name}.controller.#{action_name}")
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: I18n.t("#{controller_name}.controller.#{action_name}")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      if current_user.god
        params.require(:user).permit(:first_name, :last_name, :email, :note, :god)
      else
        params.require(:user).permit(:first_name, :last_name, :email, :note)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Sancho::ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%hr.featurette-divider
%footer
  %p.pull-right
    2014
  %p
    %span.lob 
      %span.evid AN
      OTHER Web App

app/views/layouts/_navigation.html.haml
/ Fixed navbar
.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"}= Rails.configuration.navbar_brand
    .navbar-collapse.collapse

      - if account_signed_in?
        %ul.nav.navbar-nav
          %li= link_to t('.users'), users_path

        %ul.nav.navbar-nav.navbar-right
          %li
            %button.btn.btn-danger.navbar-btn{:onclick => "window.location.href='#{destroy_account_session_url}'"}= t('.sign_out')

      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            %button.btn.btn-info.navbar-btn{:onclick => "window.location.href='#{new_account_session_url}'"}= t('.sign_in')

app/views/users/_form.html.haml
= form_for @user, :html => {:class => 'form-horizontal', :role => 'form'} do |f|
  = error_notification(@user) if @user.errors.any?

  .form-group
    = f.label :first_name, t('.first_name', :default => t("users.attributes.first_name")), class: 'col-sm-3 control-label'
    .col-sm-6
      = f.text_field :first_name, class: 'form-control', required: true
      
  .form-group
    = f.label :last_name, t('.last_name', :default => t("users.attributes.last_name")), class: 'col-sm-3 control-label'
    .col-sm-6
      = f.text_field :last_name, class: 'form-control', required: true
      
  .form-group
    = f.label :email, t('.email', :default => t("users.attributes.email")), class: 'col-sm-3 control-label'
    .col-sm-6
      = f.text_field :email, class: 'form-control', required: true
      
  .form-group
    = f.label :note, t('.note', :default => t("users.attributes.note")), class: 'col-sm-3 control-label'
    .col-sm-6
      = f.text_area :note, class: 'form-control'
  
  - if current_account.god
    .form-group
      .col-sm-offset-3.col-sm-6
        .checkbox
          %label
            = f.check_box :god
            = t('.god', :default => t("users.attributes.god"))
      
     

  .form-group
    .col-sm-offset-3.col-sm-9
      = f.submit nil, class: 'btn btn-primary'
      = link_to_back :button => :norm, :label => t(".cancel")

app/views/users/edit.html.haml
- content_for :title do
  = t('.title')

.page-header
  %h1=t '.title', :default => t('helpers.form.edit')
  
= render :partial => "form", :locals => { :on_edit => true }

app/views/users/index.html.haml
- content_for :title do
  = t('.title')

%ol.breadcrumb
  %li.active= t('.index')


.page-header
  %p.pull-right
    = link_to_new(User, new_user_path, :button => :norm, :label => t(".new"), :glyphicon  => "plus-sign")
  %h1= t('.title')

- if @users.empty?
  .alert.alert-info= t(:no_users)
- else
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th= t '.first_name', :default => t("users.attributes.first_name")
        %th= t '.last_name', :default => t("users.attributes.last_name")
        %th= t '.email', :default => t("users.attributes.email")
        %th= t '.god', :default => t("users.attributes.god")
        %th.right=t '.actions', :default => t("helpers.actions")

    %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.first_name, user
        %td= link_to user.last_name, user
        %td= link_to user.email, user
        %td= bool_to_icon(user.god)
        
        %td.right
          = link_to_show(user, user_path(user))
          = link_to_edit(user, edit_user_path(user))
          = link_to_destroy(user, user_path(user))

app/views/users/new.html.haml
- content_for :title do
  = t('.title')

.page-header
  %h1=t '.title', :default => t('helpers.form.new')
  
= render :partial => "form", :locals => { :on_edit => false }

app/views/users/show.html.haml
- content_for :title do
  = t('.title')

%ol.breadcrumb
  %li= link_to t('.index'), users_path
  %li.active= @user.full_name

.page-header.w-lead
  %p.lead= t(:user)
  %p.pull-right
    = link_to_edit(@user, edit_user_path(@user), :button => :norm, :glyphicon  => "edit")
    = link_to_destroy(@user, user_path(@user), :button => :norm, :glyphicon  => "remove-sign")
  %h1= @user.full_name

.row.record-detail
  .col-md-9
    .record-fields
      %dl.dl-horizontal
      
        %dt= t('.first_name', :default => t("users.attributes.first_name"))
        %dd= @user.first_name
      
        %dt= t('.last_name', :default => t("users.attributes.last_name"))
        %dd= @user.last_name
      
        %dt= t('.email', :default => t("users.attributes.email"))
        %dd= @user.email
      
        %dt= t('.note', :default => t("users.attributes.note"))
        %dd= @user.note
      
        %dt= t('.god', :default => t("users.attributes.god"))
        %dd= bool_to_icon(@user.god)

      %dl.dl-horizontal.buttons
        %td
        %dd= link_to_index User, users_path, :button => :norm

  .col-md-3
    = render :partial => "layouts/sancho/record_stamps", :locals => { :o => @user }